(define (let*->nested-lets seq)
  (expand-let*-clauses (other-clauses seq))
)

(define (expand-let*-clauses clauses)
  (if (null? (cdr clauses))
    (car clauses)
    (let ((var-exps (car clauses)))
      (let ((first (car var-exps)))
        (list 'let (list first)
        (expand-let*-clauses (cdr-exps))
        )
      )
    )
  )
)